// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akkdibywknlfbcbidtfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFra2RpYnl3a25sZmJjYmlkdGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODcxMDMsImV4cCI6MjA2MDY2MzEwM30.37Li5z3VsCZPslEipgllNZIFlT2PVRKkNmOvHTyh4hQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);