// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdnuwpbkbwpioxdeddkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkbnV3cGJrYndwaW94ZGVkZGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTk0NjEsImV4cCI6MjA2NDczNTQ2MX0.8tPzgQXmwHT3FfaEmf4h6ZOwRl0WmDdFJJSV3hmNn1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);